export const CONSTANTS = {
    TITLE: "Title",
    DESCRIPTION: "Description",
    PRICE: "Price",
    DISCOUNT_PERCENTAGE: "Discount percentage",
    STOCK: "Stock",
    BRAND: "Brand",
    CATEGORY: "Category",
    CLOSE: "Close",
    CONFIRM: "Confirm",
    CLEAR: "Clear",
    PASSWORD: "Password",
    REPEAT_PASSWORD: "Repeat password",
    LOGIN: "Login",
    USE_DEFAULT_VALUES: "Use default values",
    RESET: "Reset",
    NEW_USER: "New user?",
    LASTNAME: "Lastname",
    FIRSTNAME: "Firstname",
    USERNAME: "Username",
    BACK: "Back",
    IMAGES: "Images",
    MSG_CONFIRM_OPERATION: "Confirm operation",
    MSG_CONFIRM_DELETE_TITLE: "Confirm delete",
    MSG_CONFIRM_DELETE: "Are you sure you want to delete the selected product?",
    MSG_CONFIRM_FORM_TEXT: "Are you sure you want to confirm the entered data?",
    MSG_INVALID_CREDENTIALS_TITLE: "Login failed",
    MSG_INVALID_CREDENTIALS_TEXT: "Invalid credentials",
    
}